name = "SBMLCounterfactual"
uuid = "7134bbee-6c1a-4b76-8203-308ae7586252"
authors = ["Devon Kohler <devonjkohler@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Omega = "1af16e33-887a-59b3-8344-18f1671b3ade"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
